// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using euprava_sud.Data;

#nullable disable

namespace euprava_sud.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230512210605_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DokumentPrekrsajnaPrijava", b =>
                {
                    b.Property<Guid>("DokumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PrekrsajnaPrijavaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DokumentId", "PrekrsajnaPrijavaId");

                    b.HasIndex("PrekrsajnaPrijavaId");

                    b.ToTable("OdlukaSudijeDokumenti", (string)null);
                });

            modelBuilder.Entity("eUprava.Court.Model.Dokument", b =>
                {
                    b.Property<Guid>("DokumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("URLDokumenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DokumentId");

                    b.ToTable("Dokumenti");
                });

            modelBuilder.Entity("eUprava.Court.Model.Gradjanin", b =>
                {
                    b.Property<string>("Jmbg")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Broj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OpstinaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Jmbg");

                    b.HasIndex("Jmbg")
                        .IsUnique();

                    b.HasIndex("OpstinaId");

                    b.ToTable("Gradjani");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Gradjanin");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("eUprava.Court.Model.Opstina", b =>
                {
                    b.Property<Guid>("OpstinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PTT")
                        .HasColumnType("int");

                    b.HasKey("OpstinaId");

                    b.HasIndex("PTT")
                        .IsUnique();

                    b.ToTable("Opstine");
                });

            modelBuilder.Entity("eUprava.Court.Model.Predmet", b =>
                {
                    b.Property<Guid>("PredmetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdvokatJmbg")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptuzeniJmbg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PrekrsajnaPrijavaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SudijaJmbg")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PredmetId");

                    b.HasIndex("AdvokatJmbg");

                    b.HasIndex("PrekrsajnaPrijavaId");

                    b.HasIndex("SudijaJmbg");

                    b.ToTable("Predmeti");
                });

            modelBuilder.Entity("eUprava.Court.Model.PrekrsajnaPrijava", b =>
                {
                    b.Property<Guid>("PrekrsajnaPrijavaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Komentar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OpstinaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OptuzeniJmbg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Prekrsaj")
                        .HasColumnType("int");

                    b.Property<string>("PrijavljenoOdJmbg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusPrekrsajnePrijave")
                        .HasColumnType("int");

                    b.Property<string>("SudijaJmbg")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PrekrsajnaPrijavaId");

                    b.HasIndex("OpstinaId");

                    b.HasIndex("SudijaJmbg");

                    b.ToTable("PrekrsajnePrijave");
                });

            modelBuilder.Entity("eUprava.Court.Model.Rociste", b =>
                {
                    b.Property<Guid>("RocisteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdvokatJmbg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumRocista")
                        .HasColumnType("datetime2");

                    b.Property<int>("IshodRocista")
                        .HasColumnType("int");

                    b.Property<string>("OptuzeniJmbg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PredmetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SudId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SudijaJmbg")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RocisteId");

                    b.HasIndex("PredmetId");

                    b.HasIndex("SudId");

                    b.HasIndex("SudijaJmbg");

                    b.ToTable("Rocista");
                });

            modelBuilder.Entity("eUprava.Court.Model.Sud", b =>
                {
                    b.Property<Guid>("SudId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OpstinaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SudId");

                    b.HasIndex("OpstinaId");

                    b.ToTable("Sudovi");
                });

            modelBuilder.Entity("euprava_sud.Model.OdlukaSudije", b =>
                {
                    b.Property<Guid>("OdlukaSudijeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("NovcanaKazna")
                        .HasColumnType("float");

                    b.Property<int>("OduzimanjeBodova")
                        .HasColumnType("int");

                    b.Property<bool>("OduzimanjeVozacke")
                        .HasColumnType("bit");

                    b.Property<Guid>("PredmetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Resenje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RocisteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SudijaJmbg")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OdlukaSudijeId");

                    b.HasIndex("PredmetId");

                    b.HasIndex("RocisteId");

                    b.HasIndex("SudijaJmbg");

                    b.ToTable("OdlukeSudija");
                });

            modelBuilder.Entity("eUprava.Court.Model.Sudija", b =>
                {
                    b.HasBaseType("eUprava.Court.Model.Gradjanin");

                    b.Property<Guid>("SudId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("SudId");

                    b.HasDiscriminator().HasValue("Sudija");
                });

            modelBuilder.Entity("DokumentPrekrsajnaPrijava", b =>
                {
                    b.HasOne("eUprava.Court.Model.Dokument", null)
                        .WithMany()
                        .HasForeignKey("DokumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eUprava.Court.Model.PrekrsajnaPrijava", null)
                        .WithMany()
                        .HasForeignKey("PrekrsajnaPrijavaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eUprava.Court.Model.Gradjanin", b =>
                {
                    b.HasOne("eUprava.Court.Model.Opstina", "Opstina")
                        .WithMany()
                        .HasForeignKey("OpstinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Opstina");
                });

            modelBuilder.Entity("eUprava.Court.Model.Predmet", b =>
                {
                    b.HasOne("eUprava.Court.Model.Gradjanin", "Advokat")
                        .WithMany()
                        .HasForeignKey("AdvokatJmbg");

                    b.HasOne("eUprava.Court.Model.PrekrsajnaPrijava", "PrekrsajnaPrijava")
                        .WithMany()
                        .HasForeignKey("PrekrsajnaPrijavaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eUprava.Court.Model.Sudija", "Sudija")
                        .WithMany()
                        .HasForeignKey("SudijaJmbg");

                    b.Navigation("Advokat");

                    b.Navigation("PrekrsajnaPrijava");

                    b.Navigation("Sudija");
                });

            modelBuilder.Entity("eUprava.Court.Model.PrekrsajnaPrijava", b =>
                {
                    b.HasOne("eUprava.Court.Model.Opstina", "Opstina")
                        .WithMany()
                        .HasForeignKey("OpstinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eUprava.Court.Model.Sudija", "Sudija")
                        .WithMany("PrekrsajnePrijave")
                        .HasForeignKey("SudijaJmbg")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Opstina");

                    b.Navigation("Sudija");
                });

            modelBuilder.Entity("eUprava.Court.Model.Rociste", b =>
                {
                    b.HasOne("eUprava.Court.Model.Predmet", "Predmet")
                        .WithMany()
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("eUprava.Court.Model.Sud", "Sud")
                        .WithMany("Rocista")
                        .HasForeignKey("SudId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("eUprava.Court.Model.Sudija", "Sudija")
                        .WithMany()
                        .HasForeignKey("SudijaJmbg")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Predmet");

                    b.Navigation("Sud");

                    b.Navigation("Sudija");
                });

            modelBuilder.Entity("eUprava.Court.Model.Sud", b =>
                {
                    b.HasOne("eUprava.Court.Model.Opstina", "Opstina")
                        .WithMany()
                        .HasForeignKey("OpstinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Opstina");
                });

            modelBuilder.Entity("euprava_sud.Model.OdlukaSudije", b =>
                {
                    b.HasOne("eUprava.Court.Model.Predmet", "Predmet")
                        .WithMany()
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eUprava.Court.Model.Rociste", "Rociste")
                        .WithMany()
                        .HasForeignKey("RocisteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eUprava.Court.Model.Sudija", "Sudija")
                        .WithMany()
                        .HasForeignKey("SudijaJmbg")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Predmet");

                    b.Navigation("Rociste");

                    b.Navigation("Sudija");
                });

            modelBuilder.Entity("eUprava.Court.Model.Sudija", b =>
                {
                    b.HasOne("eUprava.Court.Model.Sud", "Sud")
                        .WithMany("Sudije")
                        .HasForeignKey("SudId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sud");
                });

            modelBuilder.Entity("eUprava.Court.Model.Sud", b =>
                {
                    b.Navigation("Rocista");

                    b.Navigation("Sudije");
                });

            modelBuilder.Entity("eUprava.Court.Model.Sudija", b =>
                {
                    b.Navigation("PrekrsajnePrijave");
                });
#pragma warning restore 612, 618
        }
    }
}
